base: 'https://hajeri.ddev.site/'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=9'
  -
    errorCode: 403
    errorHandler: Page
    errorContentSource: 't3://page?uid=9'
  -
    errorCode: 500
    errorHandler: Page
    errorContentSource: 't3://page?uid=9'
  -
    errorCode: 503
    errorHandler: Page
    errorContentSource: 't3://page?uid=9'
  -
    errorCode: 0
    errorHandler: Page
    errorContentSource: 't3://page?uid=9'
languages:
  -
    title: arabic
    enabled: true
    languageId: 3
    base: /
    locale: ar_SA
    navigationTitle: ''
    flag: global
    hreflang: ''
    websiteTitle: ''
    fallbackType: strict
    fallbacks: ''
  -
    title: English
    enabled: true
    languageId: 0
    base: /en/
    typo3Language: default
    locale: en_GB.UTF-8
    iso-639-1: en
    websiteTitle: ''
    navigationTitle: EN
    hreflang: en-gb
    direction: ''
    flag: gb
rootPageId: 1
routes:
  -
    route: robots.txt
    type: staticText
    content: "Sitemap: https://www.oussemaharrabi.tn/sitemap.xml\r\nSitemap: https:/www.oussemaharrabi.tn/en/sitemap.xml\r\nUser-agent: *"
websiteTitle: ''
